export const CREATE_TICKET_START: string = "CREATE_TICKET_START"
export const CREATE_TICKET_SUCCESS: string = "CREATE_TICKET_SUCCESS"
export const CREATE_TICKET_FAIL: string = "CREATE_TICKET_FAIL"

export const EDIT_TICKET_START: string = "EDIT_TICKET_START"
export const EDIT_TICKET_SUCCESS: string = "EDIT_TICKET_SUCCESS"
export const EDIT_TICKET_FAIL: string = "EDIT_TICKET_FAIL"

export const CLAIM_TICKET_START: string = "CLAIM_TICKET_START"
export const CLAIM_TICKET_SUCCESS: string = "CLAIM_TICKET_SUCCESS"
export const CLAIM_TICKET_FAIL: string = "CLAIM_TICKET_FAIL"

export const DELETE_TICKET_START: string = "DELETE_TICKET_START"
export const DELETE_TICKET_SUCCESS: string = "DELETE_TICKET_SUCCESS"
export const DELETE_TICKET_FAIL: string = "DELETE_TICKET_FAIL"